import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSupplierFields1763028266678 implements MigrationInterface {
    name = 'AddSupplierFields1763028266678'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_role_id_roles_id"`);
        await queryRunner.query(`ALTER TABLE "batches" DROP CONSTRAINT "FK_batches_shipment_id_shipments_id"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_shipments_supplier_id_suppliers_id"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_clients_created_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_clients_updated_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_sale_items_sale_id_sales_id"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_sale_items_batch_id_batches_id"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_client_id_clients_id"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_created_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_updated_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "buyback_items" DROP CONSTRAINT "FK_buyback_items_buyback_id_buybacks_id"`);
        await queryRunner.query(`ALTER TABLE "buyback_items" DROP CONSTRAINT "FK_buyback_items_original_sale_item_id_sale_items_id"`);
        await queryRunner.query(`ALTER TABLE "buybacks" DROP CONSTRAINT "FK_buybacks_original_sale_id_sales_id"`);
        await queryRunner.query(`ALTER TABLE "buybacks" DROP CONSTRAINT "FK_buybacks_client_id_clients_id"`);
        await queryRunner.query(`ALTER TABLE "buybacks" DROP CONSTRAINT "FK_buybacks_created_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "buybacks" DROP CONSTRAINT "FK_buybacks_updated_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_user_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_client_id_clients_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_buyback_id_buybacks_id"`);
        await queryRunner.query(`ALTER TABLE "write_offs" DROP CONSTRAINT "FK_write_offs_batch_id_batches_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_account_id_accounts_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_created_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_updated_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" DROP CONSTRAINT "FK_partner_withdrawals_user_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" DROP CONSTRAINT "FK_partner_withdrawals_created_by_id_users_id"`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" DROP CONSTRAINT "FK_partner_withdrawals_updated_by_id_users_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_batches_shipment_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_shipments_supplier_arrival"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sale_items_sale_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sale_items_batch_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sales_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_buyback_items_buyback_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_buyback_items_original_sale_item_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_buybacks_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_buybacks_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_write_offs_batch_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_account_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_linked_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_partner_withdrawals_user_date"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "contact_person" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "legal_entity_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "inn" character varying(12)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "kpp" character varying(9)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "ogrn" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "bank_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "bank_account" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "correspondent_account" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "bik" character varying(9)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_users_email"`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "total_cost" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."client_type_enum" RENAME TO "client_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."clients_client_type_enum" AS ENUM('individual', 'wholesaler')`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" TYPE "public"."clients_client_type_enum" USING "client_type"::"text"::"public"."clients_client_type_enum"`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" SET DEFAULT 'individual'`);
        await queryRunner.query(`DROP TYPE "public"."client_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."sale_status_enum" RENAME TO "sale_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" TYPE "public"."sales_status_enum" USING "status"::"text"::"public"."sales_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" SET DEFAULT 'completed'`);
        await queryRunner.query(`DROP TYPE "public"."sale_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."buyback_status_enum" RENAME TO "buyback_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."buybacks_status_enum" AS ENUM('planned', 'contacted', 'declined', 'completed')`);
        await queryRunner.query(`ALTER TABLE "buybacks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buybacks" ALTER COLUMN "status" TYPE "public"."buybacks_status_enum" USING "status"::"text"::"public"."buybacks_status_enum"`);
        await queryRunner.query(`ALTER TABLE "buybacks" ALTER COLUMN "status" SET DEFAULT 'planned'`);
        await queryRunner.query(`DROP TYPE "public"."buyback_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "UQ_accounts_name"`);
        await queryRunner.query(`ALTER TYPE "public"."account_type_enum" RENAME TO "account_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."accounts_type_enum" AS ENUM('cash', 'bank', 'other')`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "type" TYPE "public"."accounts_type_enum" USING "type"::"text"::"public"."accounts_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."account_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "balance" SET DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TYPE "public"."transaction_type_enum" RENAME TO "transaction_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('purchase', 'sale', 'buyback', 'write_off', 'partner_withdrawal')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "type" TYPE "public"."transactions_type_enum" USING "type"::"text"::"public"."transactions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."linked_entity_type_enum" RENAME TO "linked_entity_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_linked_entity_type_enum" AS ENUM('shipment', 'sale', 'buyback', 'write_off', 'partner_withdrawal')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "linked_entity_type" TYPE "public"."transactions_linked_entity_type_enum" USING "linked_entity_type"::"text"::"public"."transactions_linked_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."linked_entity_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."partner_withdrawal_type_enum" RENAME TO "partner_withdrawal_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."partner_withdrawals_type_enum" AS ENUM('cash', 'goods')`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" ALTER COLUMN "type" TYPE "public"."partner_withdrawals_type_enum" USING "type"::"text"::"public"."partner_withdrawals_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."partner_withdrawal_type_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_read" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_accounts_name" ON "accounts" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_account_date" ON "transactions" ("amount") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_linked_entity" ON "transactions" ("linked_entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_partner_withdrawals_user_date" ON "partner_withdrawals" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batches" ADD CONSTRAINT "FK_ae2b653f129fbde42e91738ce29" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_4e638602ea498c95d2e4f2bc109" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_c210a330b80232c29c2ad68462a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_6510bee02a86eca458a8572af6e" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c49d95226945ca3a93584f912ca" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyback_items" ADD CONSTRAINT "FK_90a997b3d813d7c428b308209cd" FOREIGN KEY ("buyback_id") REFERENCES "buybacks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyback_items" ADD CONSTRAINT "FK_0c62216bbddf469a68c59ad327a" FOREIGN KEY ("original_sale_item_id") REFERENCES "sale_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buybacks" ADD CONSTRAINT "FK_ed962f85d3d47e1e77e68249f15" FOREIGN KEY ("original_sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buybacks" ADD CONSTRAINT "FK_df10d71fc60686884311bb0bde1" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_a8e01a9c49d8d458322b2894cd9" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_32f3e31dd198397b979e64d2da5" FOREIGN KEY ("buyback_id") REFERENCES "buybacks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "write_offs" ADD CONSTRAINT "FK_6806a38d212f61fbadcfdb1306c" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_49c0d6e8ba4bfb5582000d851f0" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" ADD CONSTRAINT "FK_e74a8520bedf071faac5e2717d8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" DROP CONSTRAINT "FK_e74a8520bedf071faac5e2717d8"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_49c0d6e8ba4bfb5582000d851f0"`);
        await queryRunner.query(`ALTER TABLE "write_offs" DROP CONSTRAINT "FK_6806a38d212f61fbadcfdb1306c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_32f3e31dd198397b979e64d2da5"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_a8e01a9c49d8d458322b2894cd9"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "buybacks" DROP CONSTRAINT "FK_df10d71fc60686884311bb0bde1"`);
        await queryRunner.query(`ALTER TABLE "buybacks" DROP CONSTRAINT "FK_ed962f85d3d47e1e77e68249f15"`);
        await queryRunner.query(`ALTER TABLE "buyback_items" DROP CONSTRAINT "FK_0c62216bbddf469a68c59ad327a"`);
        await queryRunner.query(`ALTER TABLE "buyback_items" DROP CONSTRAINT "FK_90a997b3d813d7c428b308209cd"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c49d95226945ca3a93584f912ca"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_6510bee02a86eca458a8572af6e"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_c210a330b80232c29c2ad68462a"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_4e638602ea498c95d2e4f2bc109"`);
        await queryRunner.query(`ALTER TABLE "batches" DROP CONSTRAINT "FK_ae2b653f129fbde42e91738ce29"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_partner_withdrawals_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_linked_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_account_date"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_accounts_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_read"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_users_email"`);
        await queryRunner.query(`CREATE TYPE "public"."partner_withdrawal_type_enum_old" AS ENUM('cash', 'goods')`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" ALTER COLUMN "type" TYPE "public"."partner_withdrawal_type_enum_old" USING "type"::"text"::"public"."partner_withdrawal_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."partner_withdrawals_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."partner_withdrawal_type_enum_old" RENAME TO "partner_withdrawal_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."linked_entity_type_enum_old" AS ENUM('shipment', 'sale', 'buyback', 'write_off', 'partner_withdrawal')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "linked_entity_type" TYPE "public"."linked_entity_type_enum_old" USING "linked_entity_type"::"text"::"public"."linked_entity_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_linked_entity_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."linked_entity_type_enum_old" RENAME TO "linked_entity_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_type_enum_old" AS ENUM('purchase', 'sale', 'buyback', 'write_off', 'partner_withdrawal')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "type" TYPE "public"."transaction_type_enum_old" USING "type"::"text"::"public"."transaction_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."transaction_type_enum_old" RENAME TO "transaction_type_enum"`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "balance" SET DEFAULT 0.00`);
        await queryRunner.query(`CREATE TYPE "public"."account_type_enum_old" AS ENUM('cash', 'bank', 'other')`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "type" TYPE "public"."account_type_enum_old" USING "type"::"text"::"public"."account_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."account_type_enum_old" RENAME TO "account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "UQ_accounts_name" UNIQUE ("name")`);
        await queryRunner.query(`CREATE TYPE "public"."buyback_status_enum_old" AS ENUM('planned', 'contacted', 'declined', 'completed')`);
        await queryRunner.query(`ALTER TABLE "buybacks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buybacks" ALTER COLUMN "status" TYPE "public"."buyback_status_enum_old" USING "status"::"text"::"public"."buyback_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "buybacks" ALTER COLUMN "status" SET DEFAULT 'planned'`);
        await queryRunner.query(`DROP TYPE "public"."buybacks_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."buyback_status_enum_old" RENAME TO "buyback_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."sale_status_enum_old" AS ENUM('completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" TYPE "public"."sale_status_enum_old" USING "status"::"text"::"public"."sale_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" SET DEFAULT 'completed'`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sale_status_enum_old" RENAME TO "sale_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."client_type_enum_old" AS ENUM('individual', 'wholesaler')`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" TYPE "public"."client_type_enum_old" USING "client_type"::"text"::"public"."client_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" SET DEFAULT 'individual'`);
        await queryRunner.query(`DROP TYPE "public"."clients_client_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."client_type_enum_old" RENAME TO "client_type_enum"`);
        await queryRunner.query(`ALTER TABLE "shipments" ALTER COLUMN "total_cost" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_users_email" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "bik"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "correspondent_account"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "bank_account"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "bank_name"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "ogrn"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "kpp"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "inn"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "legal_entity_name"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "contact_person"`);
        await queryRunner.query(`CREATE INDEX "IDX_partner_withdrawals_user_date" ON "partner_withdrawals" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_linked_entity" ON "transactions" ("linked_entity_id", "linked_entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_account_date" ON "transactions" ("account_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_write_offs_batch_date" ON "write_offs" ("batch_id", "write_off_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_read" ON "notifications" ("is_read", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_buybacks_client_id" ON "buybacks" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_buybacks_status" ON "buybacks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_buyback_items_original_sale_item_id" ON "buyback_items" ("original_sale_item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_buyback_items_buyback_id" ON "buyback_items" ("buyback_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_sales_client_id" ON "sales" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_sale_items_batch_id" ON "sale_items" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_sale_items_sale_id" ON "sale_items" ("sale_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_shipments_supplier_arrival" ON "shipments" ("arrival_date", "supplier_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_batches_shipment_id" ON "batches" ("shipment_id") `);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" ADD CONSTRAINT "FK_partner_withdrawals_updated_by_id_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" ADD CONSTRAINT "FK_partner_withdrawals_created_by_id_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner_withdrawals" ADD CONSTRAINT "FK_partner_withdrawals_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_updated_by_id_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_created_by_id_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_account_id_accounts_id" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "write_offs" ADD CONSTRAINT "FK_write_offs_batch_id_batches_id" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_buyback_id_buybacks_id" FOREIGN KEY ("buyback_id") REFERENCES "buybacks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_client_id_clients_id" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_user_id_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buybacks" ADD CONSTRAINT "FK_buybacks_updated_by_id_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buybacks" ADD CONSTRAINT "FK_buybacks_created_by_id_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buybacks" ADD CONSTRAINT "FK_buybacks_client_id_clients_id" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buybacks" ADD CONSTRAINT "FK_buybacks_original_sale_id_sales_id" FOREIGN KEY ("original_sale_id") REFERENCES "sales"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyback_items" ADD CONSTRAINT "FK_buyback_items_original_sale_item_id_sale_items_id" FOREIGN KEY ("original_sale_item_id") REFERENCES "sale_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyback_items" ADD CONSTRAINT "FK_buyback_items_buyback_id_buybacks_id" FOREIGN KEY ("buyback_id") REFERENCES "buybacks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_updated_by_id_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_created_by_id_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_client_id_clients_id" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_sale_items_batch_id_batches_id" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_sale_items_sale_id_sales_id" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_clients_updated_by_id_users_id" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_clients_created_by_id_users_id" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_shipments_supplier_id_suppliers_id" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batches" ADD CONSTRAINT "FK_batches_shipment_id_shipments_id" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_role_id_roles_id" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
